/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author whois
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        btnCourse = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        btnfaculty = new java.awt.Label();
        label4 = new java.awt.Label();
        rightPanel = new javax.swing.JPanel();
        pcourse = new javax.swing.JPanel();
        label6 = new java.awt.Label();
        pfaculty = new javax.swing.JPanel();
        addFaculty = new java.awt.Label();
        viewFaculty = new java.awt.Label();
        p1 = new javax.swing.JPanel();
        addFacultyPanel = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        txtFaculty = new java.awt.TextField();
        button1 = new java.awt.Button();
        viewFacultyPanel = new javax.swing.JPanel();
        label5 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1600, 1080));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(102, 44, 133));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(84, 60, 109));
        jPanel2.setForeground(new java.awt.Color(84, 60, 109));

        btnHome.setAlignment(java.awt.Label.CENTER);
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidepane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, -1));

        jPanel3.setBackground(new java.awt.Color(120, 81, 160));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCourse.setAlignment(java.awt.Label.CENTER);
        btnCourse.setBackground(new java.awt.Color(84, 60, 109));
        btnCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnCourse.setPreferredSize(null);
        btnCourse.setText("Course Register");
        btnCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseMouseClicked(evt);
            }
        });
        jPanel3.add(btnCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        sidepane.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 280, 50));

        jPanel4.setBackground(new java.awt.Color(120, 81, 160));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnfaculty.setAlignment(java.awt.Label.CENTER);
        btnfaculty.setForeground(new java.awt.Color(255, 255, 255));
        btnfaculty.setText("Faculty");
        btnfaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfacultyMouseClicked(evt);
            }
        });
        jPanel4.add(btnfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 278, 50));

        sidepane.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("WHOIS");
        sidepane.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 100, 50));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 576));

        rightPanel.setBackground(new java.awt.Color(102, 255, 255));
        rightPanel.setForeground(new java.awt.Color(102, 204, 255));
        rightPanel.setLayout(new java.awt.CardLayout());

        label6.setText("This is course panel");

        javax.swing.GroupLayout pcourseLayout = new javax.swing.GroupLayout(pcourse);
        pcourse.setLayout(pcourseLayout);
        pcourseLayout.setHorizontalGroup(
            pcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcourseLayout.createSequentialGroup()
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pcourseLayout.setVerticalGroup(
            pcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcourseLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        rightPanel.add(pcourse, "card3");

        addFaculty.setAlignment(java.awt.Label.CENTER);
        addFaculty.setBackground(new java.awt.Color(255, 153, 153));
        addFaculty.setText("ADD FACULTY");
        addFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFacultyMouseClicked(evt);
            }
        });
        addFaculty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addFacultyKeyPressed(evt);
            }
        });

        viewFaculty.setAlignment(java.awt.Label.CENTER);
        viewFaculty.setBackground(new java.awt.Color(0, 204, 102));
        viewFaculty.setText("VIEW FACULTY");
        viewFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewFacultyMouseClicked(evt);
            }
        });
        viewFaculty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewFacultyKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout pfacultyLayout = new javax.swing.GroupLayout(pfaculty);
        pfaculty.setLayout(pfacultyLayout);
        pfacultyLayout.setHorizontalGroup(
            pfacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfacultyLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(addFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(viewFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(478, Short.MAX_VALUE))
        );
        pfacultyLayout.setVerticalGroup(
            pfacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfacultyLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(pfacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        rightPanel.add(pfaculty, "card4");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        rightPanel.add(p1, "card2");

        label1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 0, 204));
        label1.setText("ADD NEW FACULTY");

        txtFaculty.setCaretPosition(0);
        txtFaculty.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFaculty.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        button1.setActionCommand("ADD");
        button1.setBackground(new java.awt.Color(25, 142, 25));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("ADD");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addFacultyPanelLayout = new javax.swing.GroupLayout(addFacultyPanel);
        addFacultyPanel.setLayout(addFacultyPanelLayout);
        addFacultyPanelLayout.setHorizontalGroup(
            addFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFacultyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(addFacultyPanelLayout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(addFacultyPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(666, Short.MAX_VALUE))
        );
        addFacultyPanelLayout.setVerticalGroup(
            addFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFacultyPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(addFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(325, 325, 325))
        );

        rightPanel.add(addFacultyPanel, "card5");

        javax.swing.GroupLayout viewFacultyPanelLayout = new javax.swing.GroupLayout(viewFacultyPanel);
        viewFacultyPanel.setLayout(viewFacultyPanelLayout);
        viewFacultyPanelLayout.setHorizontalGroup(
            viewFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        viewFacultyPanelLayout.setVerticalGroup(
            viewFacultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        rightPanel.add(viewFacultyPanel, "card6");

        bg.add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 73, 960, 480));

        label5.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        label5.setForeground(new java.awt.Color(102, 44, 133));
        label5.setText("X");
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label5MousePressed(evt);
            }
        });
        bg.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_label5MouseClicked

    private void label5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_label5MousePressed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        
    }//GEN-LAST:event_formMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        p1.setVisible(true);
        btnHome.setBackground(new java.awt.Color(84,60,109));
        btnfaculty.setBackground(new java.awt.Color(120,81,160));
        btnCourse.setBackground(new java.awt.Color(120,81,160));
        pcourse.setVisible(false);
        pfaculty.setVisible(false);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseClicked
        // TODO add your handling code here:
        pcourse.setVisible(true);
        btnHome.setBackground(new java.awt.Color(120,81,160));
        btnfaculty.setBackground(new java.awt.Color(120,81,160));
        btnCourse.setBackground(new java.awt.Color(84,60,109));
        p1.setVisible(false);
        pfaculty.setVisible(false);
        
    }//GEN-LAST:event_btnCourseMouseClicked

    private void btnfacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfacultyMouseClicked
        // TODO add your handling code here:
        pfaculty.setVisible(true);
        btnHome.setBackground(new java.awt.Color(120,81,160));
        btnCourse.setBackground(new java.awt.Color(120,81,160));
        btnfaculty.setBackground(new java.awt.Color(84,60,109));
        p1.setVisible(false);
        pcourse.setVisible(false);
    }//GEN-LAST:event_btnfacultyMouseClicked

    private void addFacultyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addFacultyKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addFacultyKeyPressed

    private void addFacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFacultyMouseClicked
        // TODO add your handling code here:
        pfaculty.setVisible(false);
        addFacultyPanel.setVisible(true);
    }//GEN-LAST:event_addFacultyMouseClicked

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
            
            try{
               Class.forName("com.mysql.jdbc.Driver");
               con = DriverManager.getConnection("jdbc:mysql://localhost/smt","root","");
               if(txtFaculty.getText().isEmpty()){
                   JOptionPane.showMessageDialog(this, "You can't leave this blank");
               }else{
                   String facultyName= txtFaculty.getText();
                   pst = con.prepareStatement("insert into faculty(name) values ( ? ) ");
                   pst.setString(1, facultyName);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Faculty Successfully Created!!");
                   txtFaculty.setText("");
               }
            } catch (Exception ex) {
                
            }
            
    }//GEN-LAST:event_button1MouseClicked

    private void viewFacultyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewFacultyMouseClicked
        // TODO add your handling code here:
         pfaculty.setVisible(false);
        viewFacultyPanel.setVisible(true);
        addFacultyPanel.setVisible(false);
        
        
    }//GEN-LAST:event_viewFacultyMouseClicked

    private void viewFacultyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewFacultyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewFacultyKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label addFaculty;
    private javax.swing.JPanel addFacultyPanel;
    private javax.swing.JPanel bg;
    private java.awt.Label btnCourse;
    private java.awt.Label btnHome;
    private java.awt.Label btnfaculty;
    private java.awt.Button button1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel pcourse;
    private javax.swing.JPanel pfaculty;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel sidepane;
    private java.awt.TextField txtFaculty;
    private java.awt.Label viewFaculty;
    private javax.swing.JPanel viewFacultyPanel;
    // End of variables declaration//GEN-END:variables

    private void EXIT_ON_CLOSE() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
